language: python
virtualenv: 
  system_site_packages: true
sudo: required
addons:
  apt:
    packages:
    - yum
    - python-rpm
services:
    - docker
before_script:
  - ( cd docker && ./build-container.sh )
script:
  - pep8 --show-source --show-pep8 setup.py planex tests
  - pylint setup.py planex
  - nosetests --verbose
  - ./travis-build.sh
